'use client'
import React from 'react'
import '../../assets/styles/views/user/aboutUs/AboutUs.scss'
import '../../assets/styles/common/Common.scss'
import SectionTitle from '@/app/components/user/title/SectionTitle'
import UserHeroBannerTertiary from '@/app/components/user/banner/UserHeroBannerTertiary'
import UserPolicyContainer from '@/app/components/user/container/UserPolicyContainer'
import UserPledgeContainer from '@/app/components/user/container/UserPledgeContainer'
import UserEmployeeCardPrimary from '@/app/components/user/card/UserEmployeeCardPrimary'
import StaticDescriptionTextContainerSecondary from '@/app/components/user/container/StaticDescriptionTextContainerSecondary'
import DetailCardContainerPrimary from '@/app/components/user/container/DetailCardContainerPrimary'
import UserCaseCard from '@/app/components/user/card/UserCaseCard'
import UserReviewContainer from '@/app/components/user/container/UserReviewContainer'
export default function UserAboutUs({about}){const p=about?.page||{};const hero=p.hero||{};const team=p.team||[];const reasons=(p.reasons||[]).map(r=>({...r,icon:r.icon}));return <div className='ab' dir='rtl'><UserHeroBannerTertiary crumb={[{label:'خانه',href:'/'},{label:'درباره ما'}]} badge={hero.badge} title={hero.title} description={hero.description} primaryAction={{label:hero.primaryLabel,href:hero.primaryLink||'/contact-us'}} secondaryAction={{label:hero.secondaryLabel,href:hero.secondaryLink||'#team'}} keywords={hero.keywords||[]} chips={[]} stats={p.stats||[]} icon={<path d='M12 3v18M6 21h12M5 7h14M5 7l-3 7a3.5 3.5 0 0 0 6 0L5 7zm14 0l-3 7a3.5 3.5 0 0 0 6 0l-3-7z'/>}/><UserPolicyContainer title={p.policiesTitle} subtitle={p.policiesSubtitle} policies={p.policies||[]}/><UserPledgeContainer title={p.ethicsTitle} subtitle={p.ethicsSubtitle} pledges={p.ethics||[]} quote={p.ethicsQuote}/><div className='main-user-layout'><section id='team' className='ab-bare'><SectionTitle title={p.teamTitle} subtitle={p.teamSubtitle}/><div className='ab-grid ab-grid--4'>{team.map((m,i)=><UserEmployeeCardPrimary employee={m} i={i} key={m.name||i}/>)}</div></section></div><StaticDescriptionTextContainerSecondary containerTitle={p.principlesTitle} containerSubTitle={p.principlesSubtitle} contents={p.principles||[]}/><DetailCardContainerPrimary details={reasons} title={p.reasonsTitle} subtitle={p.reasonsSubtitle}/><div className='main-user-layout'><section className='ab-bare'><SectionTitle title={p.casesTitle} subtitle={p.casesSubtitle}/><div className='ab-grid ab-grid--3'>{(p.cases||[]).map((c,i)=><UserCaseCard content={c} i={i} key={i}/>)}</div></section></div><UserReviewContainer title={p.reviewsTitle} subtitle={p.reviewsSubtitle} reviews={p.reviews||[]}/></div>}
