'use client'
import React,{useEffect,useState} from 'react'
import dynamic from 'next/dynamic'
import Link from 'next/link'
import {useParams,useRouter} from 'next/navigation'
import {api} from '@/app/utilities/api'
import {CATEGORIES} from '@/app/data/blogs'
const RichTextEditor=dynamic(()=>import('@/app/components/admin/RichTextEditor'),{ssr:false,loading:()=> <div className='rte rte--loading'>در حال آماده‌سازی ویرایشگر…</div>})
const cats=CATEGORIES.filter(x=>x.key!=='all');const empty={slug:'',title:'',excerpt:'',category:cats[0]?.key||'family',author:'',contentHtml:'',status:'draft',metaTitle:'',metaDescription:''}
export default function AdminBlogEditor(){const {id}=useParams();const router=useRouter();const [f,setF]=useState(id?null:empty);const [err,setErr]=useState('');const set=x=>setF(v=>({...v,...x}));useEffect(()=>{if(id)api(`/api/admin/blog-posts/${id}`).then(setF).catch(e=>setErr(e.message))},[id]);const save=async(status)=>{setErr('');if(!f.title.trim())return setErr('عنوان را وارد کنید');if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(f.slug))return setErr('نامک فقط انگلیسی کوچک، عدد و خط تیره باشد');try{const p=await api(id?`/api/admin/blog-posts/${id}`:'/api/admin/blog-posts',{method:id?'PUT':'POST',body:{...f,status}});router.replace(`/admin/blog/${p.id}`)}catch(e){setErr(e.message)}};if(!f)return <div className='p-4'>در حال بارگذاری…</div>;return <div className='p-4' dir='rtl'><div className='d-flex justify-content-between mb-3'><div><Link href='/admin/blog'>← مقالات</Link><h1 className='h4 mt-2'>{id?'ویرایش مقاله':'مقاله جدید'}</h1></div><div><button className='btn btn-outline-dark ms-2' type='button' onClick={()=>save('draft')}>ذخیره پیش‌نویس</button><button className='btn btn-success' type='button' onClick={()=>save('published')}>انتشار</button></div></div>{err&&<div className='alert alert-danger'>{err}</div>}<div className='row g-3'><div className='col-lg-9'><input className='form-control form-control-lg mb-3' placeholder='عنوان مقاله' value={f.title} onChange={e=>set({title:e.target.value})}/><RichTextEditor value={f.contentHtml} onChange={contentHtml=>set({contentHtml})}/></div><div className='col-lg-3 d-grid gap-3 align-content-start'><div className='adm-card d-grid gap-2'><label>نامک (slug)</label><input className='form-control' dir='ltr' value={f.slug} onChange={e=>set({slug:e.target.value.toLowerCase().replace(/\s+/g,'-')})}/><label>دسته‌بندی</label><select className='form-select' value={f.category} onChange={e=>set({category:e.target.value})}>{cats.map(c=><option key={c.key} value={c.key}>{c.t}</option>)}</select><label>نویسنده</label><input className='form-control' value={f.author} onChange={e=>set({author:e.target.value})}/><label>خلاصه</label><textarea className='form-control' rows='5' value={f.excerpt} onChange={e=>set({excerpt:e.target.value})}/></div></div></div></div>}
