'use client'
import React,{useEffect,useState} from 'react'
import {api,ApiError} from '@/app/utilities/api'
import {useAdminAuth} from '@/app/layouts/admin/admin/AdminAuthContext'
import {SERVICES} from '@/app/data/services'
import {SITUATIONS,PATHS,DOCS,FAQ as FAMILY_FAQ} from '@/app/data/family'
import {STAGES as CRIMINAL_STAGES,RIGHTS,CLOCK,FAQ as CRIMINAL_FAQ} from '@/app/data/criminal'
import {STAGES as BUSINESS_STAGES,FLAGS,TYPES,FAQ as BUSINESS_FAQ} from '@/app/data/commercialandcorporate'
import {DEEDS,RISK_ITEMS,ROLES,FAQ as REAL_FAQ} from '@/app/data/realestate'
import {TYPES as CONTRACT_TYPES,COMPARE,STEPS,FAQ as CONTRACT_FAQ} from '@/app/data/contracts'
import {NOTICES,STAIRS,FAQ as TAX_FAQ} from '@/app/data/administrativeandtax'
const CONFIG={family:['حقوق خانواده',[['situations','موقعیت‌ها',SITUATIONS],['paths','مسیرها',PATHS],['docs','مدارک',DOCS],['faq','سؤالات متداول',FAMILY_FAQ]]],criminal:['دعاوی کیفری',[['stages','مراحل',CRIMINAL_STAGES],['rights','حقوق',RIGHTS],['clocks','زمان‌های مهم',CLOCK],['faq','سؤالات متداول',CRIMINAL_FAQ]]],business:['تجارت و شرکت‌ها',[['stages','مراحل',BUSINESS_STAGES],['risk','نشانه‌های خطر',FLAGS],['types','انواع شرکت',TYPES],['faq','سؤالات متداول',BUSINESS_FAQ]]],'real-estate':['املاک و ثبت اسناد',[['deeds','انواع سند',DEEDS],['risk','موارد بررسی ریسک',RISK_ITEMS],['roles','نقش‌ها',ROLES],['faq','سؤالات متداول',REAL_FAQ]]],contracts:['قراردادها و مشاوره',[['types','انواع قرارداد',CONTRACT_TYPES],['compare','مقایسه بندها',COMPARE],['steps','مراحل',STEPS],['faq','سؤالات متداول',CONTRACT_FAQ]]],tax:['اداری و مالیاتی',[['notices','ابلاغیه‌ها',NOTICES],['stairs','مراحل رسیدگی',STAIRS],['faq','سؤالات متداول',TAX_FAQ]]]}
const Field=({label,value,onChange,area=false})=><label className='d-block mb-3'><span className='form-label'>{label}</span>{area?<textarea className='form-control' rows={3} value={value??''} onChange={e=>onChange(e.target.value)}/>:<input className='form-control' value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>
const keys=x=>Object.keys(x||{}).filter(k=>typeof x[k]==='string'&&k!=='icon'&&k!=='s')
function List({label,items,onChange}){const update=(i,k,v)=>onChange(items.map((x,j)=>j===i?{...x,[k]:v}:x));return <div className='adm-card mb-3'><div className='d-flex justify-content-between'><h2 className='h5'>{label} ({items.length})</h2><button type='button' className='btn btn-sm btn-outline-primary' onClick={()=>onChange([...items,{title:'',t:'',text:''}])}>+ افزودن</button></div>{items.map((x,i)=><div className='border rounded p-3 mb-2' key={i}>{typeof x==='string'?<Field label={`آیتم ${i+1}`} value={x} onChange={v=>onChange(items.map((z,j)=>j===i?v:z))}/>:keys(x).map(k=><Field key={k} label={k} value={x[k]} onChange={v=>update(i,k,v)} area={['text','description','summary','quote','body','next','short','heading','practice','sum','l'].includes(k)}/>)}<button type='button' className='btn btn-sm btn-outline-danger' onClick={()=>onChange(items.filter((_,j)=>j!==i))}>حذف آیتم</button></div>)}</div>}
export default function AdminServiceContent({slug='services'}){const {expire}=useAdminAuth();const [form,setForm]=useState(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const cfg=CONFIG[slug];useEffect(()=>{api(`/api/admin/pages/${slug}`).then(r=>{const c=r.content||{};setForm({hero:{...c.hero},items:c.services||c.items||SERVICES,sections:Object.fromEntries((cfg?.[1]||[]).map(([k,,d])=>[k,c.sections?.[k]||d])),cta:{...(c.cta||{})}})}).catch(e=>{if(e instanceof ApiError&&e.status===401)expire();else setError(e.message)})},[slug,expire]);if(!form)return <div className='p-4'>{error||'در حال بارگذاری…'}</div>;const setHero=(k,v)=>setForm(f=>({...f,hero:{...f.hero,[k]:v}));const save=async e=>{e.preventDefault();try{await api(`/api/admin/pages/${slug}`,{method:'PUT',body:{content:{...form,services:slug==='services'?form.items:undefined}}});setNotice('تغییرات ذخیره شد.')}catch(e){setError(e.message)}};return <form onSubmit={save} className='p-4 d-grid gap-3' dir='rtl'><h1 className='h4'>ویرایش صفحه {cfg?.[0]||'خدمات'}</h1><div className='adm-card'><Field label='عنوان' value={form.hero?.title} onChange={v=>setHero('title',v)}/><Field label='برچسب' value={form.hero?.badge} onChange={v=>setHero('badge',v)}/><Field label='توضیحات' value={form.hero?.description} onChange={v=>setHero('description',v)} area/></div>{cfg?cfg[1].map(([k,l])=><List key={k} label={l} items={form.sections[k]||[]} onChange={v=>setForm(f=>({...f,sections:{...f.sections,[k]:v}}))}/>):<List label='خدمات' items={form.items} onChange={v=>setForm(f=>({...f,items:v}))}/>}<div className='adm-card'><Field label='عنوان دعوت به تماس' value={form.cta?.title} onChange={v=>setForm(f=>({...f,cta:{...f.cta,title:v}}))}/><Field label='توضیحات دعوت به تماس' value={form.cta?.subtitle} onChange={v=>setForm(f=>({...f,cta:{...f.cta,subtitle:v}}))} area/></div>{error&&<div className='alert alert-danger'>{error}</div>}{notice&&<div className='alert alert-success'>{notice}</div>}<button className='btn btn-success'>ذخیره تغییرات</button></form>}
