'use client'
import React,{useEffect,useState} from 'react'
import {api,API_URL} from '@/app/utilities/api'
import {ApiError} from '@/app/utilities/api'
import {useAdminAuth} from '@/app/layouts/admin/admin/AdminAuthContext'
import ImageUploadField from '@/app/components/admin/ImageUploadField'
import {COLLEAGUES} from '@/app/data/colleagues'
const empty={hero:{title:'همکاران حقوقی ما',description:'',indexTitle:'فهرست همکاران'},cta:{title:'می‌خواهید با یکی از همکاران صحبت کنید؟',subtitle:'موضوع پرونده را بنویسید تا به همکار مرتبط ارجاع دهیم.',actionLabel:'تماس با ما',actionHref:'/contact-us'},colleagues:[]}
const normalize=d=>({hero:{...empty.hero,...(d?.content?.hero||{})},cta:{...empty.cta,...(d?.content?.cta||{})},colleagues:(d?.content?.colleagues?.length?d.content.colleagues:COLLEAGUES).map(c=>({...c,bio:c.bio||[],education:c.education||[],honors:c.honors||[]}))})
const Field=({label,value,onChange,area=false,type='text'})=><label className='d-block mb-3'><span className='form-label mb-1'>{label}</span>{area?<textarea className='form-control' rows={3} value={value??''} onChange={e=>onChange(e.target.value)}/>:<input className='form-control' type={type} value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>
function Lines({label,items,onChange}){return <div className='border rounded-3 p-3 mb-3'><div className='d-flex justify-content-between align-items-center mb-2'><strong>{label}</strong><button type='button' className='btn btn-sm btn-outline-primary' onClick={()=>onChange([...items,''])}>+ افزودن</button></div>{items.map((x,i)=><div className='d-flex gap-2 mb-2' key={i}><textarea className='form-control' rows={2} value={x} onChange={e=>onChange(items.map((v,j)=>j===i?e.target.value:v))}/><button type='button' className='btn btn-sm btn-outline-danger align-self-start' onClick={()=>onChange(items.filter((_,j)=>j!==i))}>حذف</button></div>)}</div>}
function Timeline({label,items,onChange}){const update=(i,k,v)=>onChange(items.map((x,j)=>j===i?{...x,[k]:v}:x));return <div className='border rounded-3 p-3 mb-3'><div className='d-flex justify-content-between align-items-center mb-2'><strong>{label}</strong><button type='button' className='btn btn-sm btn-outline-primary' onClick={()=>onChange([...items,{year:'',title:'',text:''}])}>+ افزودن</button></div>{items.map((x,i)=><div className='border rounded-2 p-3 mb-2' key={i}><div className='row g-2'><div className='col-md-2'><Field label='سال' value={x.year} onChange={v=>update(i,'year',v)}/></div><div className='col-md-5'><Field label='عنوان' value={x.title} onChange={v=>update(i,'title',v)}/></div><div className='col-md-5'><Field label='توضیح' value={x.text} onChange={v=>update(i,'text',v)}/></div></div><button type='button' className='btn btn-sm btn-outline-danger' onClick={()=>onChange(items.filter((_,j)=>j!==i))}>حذف</button></div>)}</div>}
function Colleague({value,index,onChange,onRemove}){const set=(k,v)=>onChange({...value,[k]:v});return <div className='adm-card mb-3'><div className='d-flex justify-content-between align-items-center mb-3'><h2 className='h5 mb-0'>همکار {index+1}</h2><button type='button' className='btn btn-sm btn-outline-danger' onClick={onRemove}>حذف همکار</button></div><div className='row g-3'><div className='col-md-6'><Field label='نام و نام خانوادگی' value={value.name} onChange={v=>set('name',v)}/></div><div className='col-md-6'><Field label='شناسه صفحه (slug)' value={value.slug} onChange={v=>set('slug',v)}/></div><div className='col-md-6'><Field label='حوزه تخصصی' value={value.field} onChange={v=>set('field',v)}/></div><div className='col-md-6'><Field label='سمت' value={value.role} onChange={v=>set('role',v)}/></div><div className='col-12'><Field label='معرفی کوتاه' value={value.intro} onChange={v=>set('intro',v)} area/></div><div className='col-md-6'><Field label='لینکدین' value={value.linkedin} onChange={v=>set('linkedin',v)}/></div><div className='col-md-6'><ImageUploadField label='تصویر' value={value.photo?{path:value.photo,url:value.photo.startsWith('/uploads/')?`${API_URL}${value.photo}`:value.photo}:null} onChange={v=>set('photo',v?.path||null)} onError={()=>{}}/></div></div><Lines label='بیوگرافی (هر خط یک پاراگراف)' items={value.bio||[]} onChange={v=>set('bio',v)}/><Timeline label='تحصیلات' items={value.education||[]} onChange={v=>set('education',v)}/><Timeline label='سوابق و افتخارات' items={value.honors||[]} onChange={v=>set('honors',v)}/></div>}
export default function AdminColleagues(){const {expire}=useAdminAuth();const [form,setForm]=useState(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [saving,setSaving]=useState(false);useEffect(()=>{api('/api/admin/pages/colleagues').then(d=>setForm(normalize(d))).catch(e=>{if(e instanceof ApiError&&e.status===401)expire();else setError(e.message)})},[expire]);const set=(k,v)=>setForm(f=>({...f,[k]:v}));const save=async e=>{e.preventDefault();setSaving(true);setError('');try{await api('/api/admin/pages/colleagues',{method:'PUT',body:{content:form}});setNotice('تغییرات صفحه همکاران ذخیره شد.')}catch(e){setError(e.message)}finally{setSaving(false)}};if(error&&!form)return <div className='alert alert-danger m-4'>{error}</div>;if(!form)return <div className='p-4'>در حال بارگذاری…</div>;return <form onSubmit={save} className='p-4 d-grid gap-3' dir='rtl'><div><h1 className='h4 mb-1'>ویرایش صفحه همکاران</h1><p className='text-secondary mb-0'>هر بخش صفحه فیلدهای جداگانه دارد؛ JSON لازم نیست.</p></div><div className='adm-card'><h2 className='h5'>بنر صفحه</h2><Field label='عنوان صفحه' value={form.hero.title} onChange={v=>set('hero',{...form.hero,title:v})}/><Field label='توضیحات' value={form.hero.description} onChange={v=>set('hero',{...form.hero,description:v})} area/><Field label='عنوان فهرست همکاران' value={form.hero.indexTitle} onChange={v=>set('hero',{...form.hero,indexTitle:v})}/></div><div><div className='d-flex justify-content-between align-items-center mb-2'><h2 className='h5 mb-0'>اعضای تیم ({form.colleagues.length})</h2><button type='button' className='btn btn-primary btn-sm' onClick={()=>set('colleagues',[...form.colleagues,{slug:'',name:'',field:'',role:'',intro:'',photo:null,bio:[],education:[],honors:[],linkedin:''}])}>+ افزودن همکار</button></div>{form.colleagues.map((c,i)=><Colleague key={i} value={c} index={i} onChange={v=>set('colleagues',form.colleagues.map((x,j)=>j===i?v:x))} onRemove={()=>set('colleagues',form.colleagues.filter((_,j)=>j!==i))}/>)}</div><div className='adm-card'><h2 className='h5'>دعوت به تماس</h2><Field label='عنوان' value={form.cta.title} onChange={v=>set('cta',{...form.cta,title:v})}/><Field label='توضیحات' value={form.cta.subtitle} onChange={v=>set('cta',{...form.cta,subtitle:v})} area/><Field label='متن دکمه' value={form.cta.actionLabel} onChange={v=>set('cta',{...form.cta,actionLabel:v})}/><Field label='لینک دکمه' value={form.cta.actionHref} onChange={v=>set('cta',{...form.cta,actionHref:v})}/></div>{error&&<div className='alert alert-danger'>{error}</div>}{notice&&<div className='alert alert-success'>{notice}</div>}<button className='btn btn-success' disabled={saving}>{saving?'در حال ذخیره…':'ذخیره تغییرات'}</button></form>}
