'use client'
import React,{useEffect,useState} from 'react'
import {api,ApiError} from '@/app/utilities/api'
import {useAdminAuth} from '@/app/layouts/admin/admin/AdminAuthContext'
import {SERVICES} from '@/app/data/services'
import {SITUATIONS,PATHS,DOCS,FAQ as FAMILY_FAQ,LAWYER} from '@/app/data/family'
import {STAGES as CRIMINAL_STAGES,RIGHTS,CLOCK,FAQ as CRIMINAL_FAQ} from '@/app/data/criminal'
import {STAGES as BUSINESS_STAGES,FLAGS,TYPES,FAQ as BUSINESS_FAQ} from '@/app/data/commercialandcorporate'
import {DEEDS,RISK_ITEMS,ROLES,FAQ as REAL_FAQ} from '@/app/data/realestate'
import {TYPES as CONTRACT_TYPES,COMPARE,STEPS,FAQ as CONTRACT_FAQ} from '@/app/data/contracts'
import {NOTICES,STAIRS,FAQ as TAX_FAQ} from '@/app/data/administrativeandtax'
const DETAILS={family:{label:'حقوق خانواده',hero:'پیش از دادگاه، یک گفتگو',sections:[['situations','موقعیت‌ها',SITUATIONS],['paths','مسیرها',PATHS],['docs','مدارک',DOCS],['faq','سؤالات متداول',FAMILY_FAQ]]},criminal:{label:'دعاوی کیفری',hero:'دفاع از ساعت‌های اول',sections:[['stages','مراحل',CRIMINAL_STAGES],['rights','حقوق',RIGHTS],['clocks','زمان‌ها',CLOCK],['faq','سؤالات متداول',CRIMINAL_FAQ]]},business:{label:'تجارت و شرکت‌ها',hero:'کسب‌وکارتان را از روز اول ببندید',sections:[['stages','مراحل',BUSINESS_STAGES],['risk','نشانه‌های خطر',FLAGS],['types','انواع شرکت',TYPES],['faq','سؤالات متداول',BUSINESS_FAQ]]},'real-estate':{label:'املاک و ثبت اسناد',hero:'یک سند، هزار داستان',sections:[['deeds','انواع سند',DEEDS],['risk','موارد بررسی ریسک',RISK_ITEMS],['roles','نقش‌ها',ROLES],['faq','سؤالات متداول',REAL_FAQ]]},contracts:{label:'قراردادها و مشاوره',hero:'پیش از امضا، یک نگاه دوم',sections:[['types','انواع قرارداد',CONTRACT_TYPES],['compare','مقایسه بندها',COMPARE],['steps','مراحل',STEPS],['faq','سؤالات متداول',CONTRACT_FAQ]]},tax:{label:'دعاوی اداری و مالیاتی',hero:'برگ تشخیص گرفته‌اید؟ مهلت دارید',sections:[['notices','ابلاغیه‌ها',NOTICES],['stairs','مراحل رسیدگی',STAIRS],['faq','سؤالات متداول',TAX_FAQ]]}}
const Field=({label,value,onChange,area=false})=><label className='d-block mb-3'><span className='form-label mb-1'>{label}</span>{area?<textarea className='form-control' rows={3} value={value??''} onChange={e=>onChange(e.target.value)}/>:<input className='form-control' value={value??''} onChange={e=>onChange(e.target.value)}/>}</label>
const textFields=(obj)=>Object.keys(obj||{}).filter(k=>typeof obj[k]==='string'&&k!=='icon'&&k!=='s')
function ItemList({label,items,onChange}){const update=(i,k,v)=>onChange(items.map((x,j)=>j===i?{...x,[k]:v}:x));return <div className='adm-card mb-3'><div className='d-flex justify-content-between mb-2'><strong>{label} ({items.length})</strong><button type='button' className='btn btn-sm btn-outline-primary' onClick={()=>onChange([...items,{title:'',t:'',text:''}])}>+ افزودن</button></div>{items.map((x,i)=><div className='border rounded-2 p-3 mb-2' key={i}>{typeof x==='string'?<Field label={`آیتم ${i+1}`} value={x} onChange={v=>onChange(items.map((z,j)=>j===i?v:z))}/>:<>{textFields(x).map(k=><Field key={k} label={k} value={x[k]} onChange={v=>update(i,k,v)} area={['text','description','summary','quote','body','next','short','heading','practice','sum','l'].includes(k)}/>)}<button type='button' className='btn btn-sm btn-outline-danger' onClick={()=>onChange(items.filter((_,j)=>j!==i))}>حذف</button></>}</div>)}</div>}
export default function AdminServiceContent({slug='services'}){const {expire}=useAdminAuth();const cfg=DETAILS[slug];const [form,setForm]=useState(null);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [saving,setSaving]=useState(false);useEffect(()=>{api(`/api/admin/pages/${slug}`).then(d=>{const c=d.content||{};setForm({hero:{title:c.hero?.title||cfg?.hero||'خدمات حقوقی',badge:c.hero?.badge||'',description:c.hero?.description||''},items:c.items||c.services||(!cfg?SERVICES:[]),cta:{title:c.cta?.title||'برای شروع با ما تماس بگیرید',subtitle:c.cta?.subtitle||'',actionLabel:c.cta?.actionLabel||'تماس با ما',actionHref:c.cta?.actionHref||'/contact-us'},sections:Object.fromEntries((cfg?.sections||[]).map(([k,l,d])=>[k,c[k]||d]))})}).catch(e=>{if(e instanceof ApiError&&e.status===401)expire();else setError(e.message)})},[slug,expire]);const save=async e=>{e.preventDefault();setSaving(true);try{await api(`/api/admin/pages/${slug}`,{method:'PUT',body:{content:form}});setNotice('تغییرات ذخیره شد.')}catch(e){setError(e.message)}finally{setSaving(false)}};if(!form)return <div className='p-4'>{error||'در حال بارگذاری…'}</div>;return <form onSubmit={save} className='p-4 d-grid gap-3' dir='rtl'><h1 className='h4'>ویرایش صفحه {cfg?.label||'خدمات'}</h1><div className='adm-card'><h2 className='h5'>بنر صفحه</h2><Field label='عنوان' value={form.hero.title} onChange={v=>setForm({...form,hero:{...form.hero,title:v}})}/><Field label='برچسب' value={form.hero.badge} onChange={v=>setForm({...form,hero:{...form.hero,badge:v}})}/><Field label='توضیحات' value={form.hero.description} onChange={v=>setForm({...form,hero:{...form.hero,description:v}})} area/></div>{cfg?cfg.sections.map(([k,l])=><ItemList key={k} label={l} items={form.sections[k]||[]} onChange={v=>setForm({...form,sections:{...form.sections,[k]:v}})}/>):<ItemList label='خدمات' items={form.items} onChange={v=>setForm({...form,items:v})}/>}<div className='adm-card'><h2 className='h5'>دعوت به تماس</h2><Field label='عنوان' value={form.cta.title} onChange={v=>setForm({...form,cta:{...form.cta,title:v}})}/><Field label='توضیحات' value={form.cta.subtitle} onChange={v=>setForm({...form,cta:{...form.cta,subtitle:v}})} area/><Field label='متن دکمه' value={form.cta.actionLabel} onChange={v=>setForm({...form,cta:{...form.cta,actionLabel:v}})}/><Field label='لینک دکمه' value={form.cta.actionHref} onChange={v=>setForm({...form,cta:{...form.cta,actionHref:v}})}/></div>{error&&<div className='alert alert-danger'>{error}</div>}{notice&&<div className='alert alert-success'>{notice}</div>}<button className='btn btn-success' disabled={saving}>{saving?'در حال ذخیره…':'ذخیره تغییرات'}</button></form>}
