'use client'
import React from 'react'
import '../../assets/styles/views/user/aboutUs/AboutUs.scss'
import '../../assets/styles/views/user/blogs/Blogs.scss'
import '../../assets/styles/common/Common.scss'
import '../../assets/styles/views/user/colleagues/Colleagues.scss'
import MainUserLayout from '../../layouts/admin/user/MainUserLayout'
import UserHeroBannerQuaternary from '@/app/components/user/banner/UserHeroBannerQuaternary'
import UserColleagueProfile from '@/app/components/user/container/UserColleagueProfile'
import UserCtaContainer from '@/app/components/user/container/UserCtaContainer'
import { COLLEAGUES, DIGITS } from '@/app/data/colleagues'
import { ARTICLES, CATEGORIES, ICONS } from '@/app/data/blogs'
export default function UserColleagues({ content }) { const hero=content?.hero||{}; const colleagues=content?.colleagues?.length?content.colleagues:COLLEAGUES; const c=content?.cta||{}; return <MainUserLayout><div className='ab tm' dir='rtl'><UserHeroBannerQuaternary crumb={[{label:'خانه',href:'/'},{label:'همکاران'}]} title={hero.title||<>همکاران <em>حقوقی</em> ما</>} description={hero.description||'این یک متن نمونه است. با وکلا و مشاورانی آشنا شوید که پرونده شما را به عهده می‌گیرند؛ تحصیلات، سوابق و مطالبی که نوشته‌اند.'} indexTitle={hero.indexTitle||'فهرست همکاران'} indexItems={colleagues.map(x=>({label:x.name,href:`#${x.slug}`}))} digits={DIGITS}/>{colleagues.map((colleague,i)=><UserColleagueProfile key={colleague.slug||i} colleague={colleague} posts={ARTICLES.filter(a=>a.author===colleague.name)} categories={CATEGORIES} icons={ICONS} index={i} digits={DIGITS} tone={i%2?'navy':'bone'}/>)}<UserCtaContainer title={c.title||'می‌خواهید با یکی از همکاران صحبت کنید؟'} subtitle={c.subtitle||'موضوع پرونده را بنویسید تا به همکار مرتبط ارجاع دهیم.'} action={{href:c.actionHref||'/contact-us',label:c.actionLabel||'تماس با ما'}}/></div></MainUserLayout>}
