import React from 'react'
import '../../assets/styles/views/user/aboutUs/AboutUs.scss'
import '../../assets/styles/common/Common.scss'
import MainUserLayout from '@/app/layouts/admin/user/MainUserLayout'
import UserHeroBannerTertiary from '@/app/components/user/banner/UserHeroBannerTertiary'
import StageExplorerContainer from '@/app/components/user/container/StageExplorerContainer'
import RiskScanContainer from '@/app/components/user/container/RiskScanContainer'
import CompareCardsContainer from '@/app/components/user/container/CompareCardsContainer'
import StaticDescriptionTextContainerSecondary from '@/app/components/user/container/StaticDescriptionTextContainerSecondary'
import UserCtaContainer from '@/app/components/user/container/UserCtaContainer'
import { DIGITS } from '@/app/data/services'
import { BUILDING, CHIPS, FAQ, FLAGS, RISK_LABELS, STAGES, TYPES } from '@/app/data/commercialandcorporate'
const titleNode=(x,f)=><>{String(x||f).split(/\{\{(.+?)\}\}/g).map((p,i)=>i%2?<em key={i}>{p}</em>:p)}</>
export default function UserBusinessPage({content}){const h=content?.hero||{},s=content?.sections||{},c=content?.cta||{};return <MainUserLayout><div className='ab bz' dir='rtl'><UserHeroBannerTertiary crumb={[{label:'خانه',href:'/'},{label:'خدمات حقوقی',href:'/services'},{label:'حقوق تجارت و شرکت‌ها'}]} badge={h.badge||'مشاوره پیش از ثبت و پیش از امضا'} title={titleNode(h.title,'کسب‌وکارتان را از {{روز اول}} ببندید')} description={h.description||'این یک متن نمونه است.'} primaryAction={{href:h.primaryHref||'#',label:h.primaryLabel||'مشاوره برای شرکت من'}} secondaryAction={{href:h.secondaryHref||'#stage',label:h.secondaryLabel||'مرحلهٔ کسب‌وکارم کدام است؟'}} icon={<path d={BUILDING}/>} chips={CHIPS}/><StageExplorerContainer id='stage' title={s.stagesTitle||'الان در کدام مرحله‌اید؟'} subtitle={s.stagesSubtitle||'یکی را از فهرست انتخاب کنید تا جزئیاتش را ببینید.'} stages={s.stages||STAGES} digits={DIGITS} icon={<path d={BUILDING}/>} /><RiskScanContainer title={s.riskTitle||'قراردادتان چند نشانهٔ خطر دارد؟'} subtitle={s.riskSubtitle||'هر موردی که در قرارداد شما وجود دارد را علامت بزنید.'} flags={s.risk||FLAGS} labels={s.riskLabels||RISK_LABELS} action={{href:s.riskHref||'#',label:s.riskActionLabel||'بازبینی این قرارداد'}}/><CompareCardsContainer title={s.typesTitle||'کدام نوع شرکت مناسب شماست؟'} subtitle={s.typesSubtitle||'این یک متن نمونه است. مقایسه‌ای کلی؛ تصمیم نهایی در جلسهٔ مشاوره گرفته می‌شود.'} items={s.types||TYPES}/><StaticDescriptionTextContainerSecondary containerTitle={s.faqTitle||'قبل از تماس، شاید بپرسید'} contents={s.faq||FAQ}/><UserCtaContainer title={c.title||'کسب‌وکارتان لایق قرارداد درست است.'} subtitle={c.subtitle||'یک جلسهٔ مشاوره، پیش از هر ثبت یا امضایی.'} action={{href:c.actionHref||'/contact-us',label:c.actionLabel||'مشاوره برای شرکت من'}}/></div></MainUserLayout>}
