import React from 'react'
import '../../assets/styles/views/user/aboutUs/AboutUs.scss'
import '../../assets/styles/common/Common.scss'
import MainUserLayout from '@/app/layouts/admin/user/MainUserLayout'
import UserHeroBannerTertiary from '@/app/components/user/banner/UserHeroBannerTertiary'
import ContractTypeContainer from '@/app/components/user/container/ContractTypeContainer'
import ClauseCompareContainer from '@/app/components/user/container/ClauseCompareContainer'
import StepCardsContainer from '@/app/components/user/container/StepCardsContainer'
import StaticDescriptionTextContainerSecondary from '@/app/components/user/container/StaticDescriptionTextContainerSecondary'
import UserCtaContainer from '@/app/components/user/container/UserCtaContainer'
import { DIGITS } from '@/app/data/services'
import { CHIPS, COMPARE, FAQ, PEN, STEPS, TYPES } from '@/app/data/contracts'
export default function UserContractsPage(){return <MainUserLayout><div className='ab ct' dir='rtl'><UserHeroBannerTertiary crumb={[{label:'خانه',href:'/'},{label:'خدمات حقوقی',href:'/services'},{label:'قراردادها و مشاورهٔ حقوقی'}]} badge='بازبینی پیش از هر امضا' title={<>پیش از امضا، <em>یک نگاه دوم</em></>} description='این یک متن نمونه است. بیشتر دعواهای حقوقی از یک قرارداد ضعیف شروع می‌شوند، نه از یک اتفاق ناگهانی. یک بازبینی دقیق، ارزان‌تر از یک دعوای طولانی است.' primaryAction={{href:'#',label:'ارسال قرارداد برای بررسی'}} secondaryAction={{href:'#type',label:'نوع قراردادم کدام است؟'}} icon={<path d={PEN}/>} chips={CHIPS}/><ContractTypeContainer id='type' title='قراردادتان دربارهٔ چیست؟' subtitle='یکی را انتخاب کنید تا بندهای کلیدی همان نوع قرارداد را ببینید.' types={TYPES} digits={DIGITS}/><ClauseCompareContainer title='یک بند مبهم، در برابر یک بند روشن' subtitle='با فلش‌ها نمونه‌های دیگر را هم ببینید. (نمونه‌اند و باید متناسب با قرارداد شما نوشته شوند.)' items={COMPARE} digits={DIGITS}/><StepCardsContainer title='از ارسال قرارداد تا نسخهٔ نهایی' steps={STEPS} digits={DIGITS}/><StaticDescriptionTextContainerSecondary containerTitle='قبل از تماس، شاید بپرسید' contents={FAQ}/><UserCtaContainer title='قراردادتان را امضا نکنید؛ اول نشانش دهید.' subtitle='بازبینی اولیه سریع است و شما را متعهد به ادامه نمی‌کند.' action={{href:'/contact-us',label:'ارسال قرارداد برای بررسی'}}/></div></MainUserLayout>}
