import React from 'react'
import '../../assets/styles/views/user/aboutUs/AboutUs.scss'
import '../../assets/styles/common/Common.scss'
import MainUserLayout from '@/app/layouts/admin/user/MainUserLayout'
import UserHeroBannerTertiary from '@/app/components/user/banner/UserHeroBannerTertiary'
import SituationTabsContainer from '@/app/components/user/container/SituationTabsContainer'
import PathSwitchContainer from '@/app/components/user/container/PathSwitchContainer'
import DocsChecklistContainer from '@/app/components/user/container/DocsChecklistContainer'
import LawyerAsideCard from '@/app/components/user/card/LawyerAsideCard'
import StaticDescriptionTextContainerSecondary from '@/app/components/user/container/StaticDescriptionTextContainerSecondary'
import UserCtaContainer from '@/app/components/user/container/UserCtaContainer'
import { DIGITS } from '@/app/data/services'
import { CHIPS, DOCS, FAQ, HEART, LAWYER, PATHS, SITUATIONS } from '@/app/data/family'
export default function UserFamilyPage(){return <MainUserLayout><div className='ab fs' dir='rtl'><UserHeroBannerTertiary crumb={[{label:'خانه',href:'/'},{label:'خدمات حقوقی',href:'/services'},{label:'حقوق خانواده'}]} badge='جلسهٔ اول کاملاً محرمانه' title={<>پیش از دادگاه، <em>یک گفتگو</em></>} description='این یک متن نمونه است. در حقوق خانواده هر پرونده پشت خودش یک زندگی دارد. اول گوش می‌دهیم، بعد بهترین مسیر را با هم انتخاب می‌کنیم.' primaryAction={{href:'#',label:'رزرو جلسهٔ مشاوره'}} secondaryAction={{href:'#situation',label:'وضعیتم کدام است؟'}} icon={<path d={HEART}/>} iconClassName='fs-heart' chips={CHIPS}/><SituationTabsContainer id='situation' title='مسئلهٔ شما کدام است؟' subtitle='یکی را انتخاب کنید تا ببینید ما چه می‌کنیم و چه مدتی طول می‌کشد.' situations={SITUATIONS} digits={DIGITS}/><PathSwitchContainer title='توافقی یا قضایی؟' subtitle='مسیر را عوض کنید و ببینید مراحل و حال‌وهوای کار چه فرقی می‌کند. (زمان‌ها و درصدها نمونه‌اند.)' paths={PATHS}/><DocsChecklistContainer title='برای جلسهٔ اول چه بیاورید؟' subtitle='هر چه دارید علامت بزنید؛ نبودن بعضی مدارک مانع شروع نیست.' docs={DOCS} aside={<LawyerAsideCard {...LAWYER}/>}/><StaticDescriptionTextContainerSecondary containerTitle='قبل از تماس، شاید بپرسید' contents={FAQ}/><UserCtaContainer title='هر چه هست، از همین‌جا شروع می‌شود.' subtitle='یک جلسهٔ مشاوره، بدون تعهد و کاملاً محرمانه.' action={{href:'/contact-us',label:'رزرو جلسهٔ مشاوره'}}/></div></MainUserLayout>}
