import React from 'react'
import '../../assets/styles/views/user/aboutUs/AboutUs.scss'
import '../../assets/styles/common/Common.scss'
import MainUserLayout from '../../layouts/admin/user/MainUserLayout'
import UserHeroBannerTertiary from '@/app/components/user/banner/UserHeroBannerTertiary'
import DeadlineFinderContainer from '@/app/components/user/container/DeadlineFinderContainer'
import StairsContainer from '@/app/components/user/container/StairsContainer'
import CaseResultContainer from '@/app/components/user/container/CaseResultContainer'
import StaticDescriptionTextContainerSecondary from '@/app/components/user/container/StaticDescriptionTextContainerSecondary'
import UserCtaContainer from '@/app/components/user/container/UserCtaContainer'
import {DIGITS} from '@/app/data/services'
import {CHIPS,DOC_ICON,FAQ,NOTICES,STAIRS} from '@/app/data/administrativeandtax'
const titleNode=(x,f)=><>{String(x||f).split(/\{\{(.+?)\}\}/g).map((p,i)=>i%2?<em key={i}>{p}</em>:p)}</>
export default function UserAdministrativeAndTax({content}){const h=content?.hero||{},s=content?.sections||{},c=content?.cta||{},r=content?.caseResult||{};return <MainUserLayout><div className='ab' dir='rtl'><UserHeroBannerTertiary crumb={[{label:'خانه',href:'/'},{label:'خدمات حقوقی',href:'/services'},{label:'دعاوی اداری و مالیاتی'}]} badge={h.badge||'اعتراض در مهلت قانونی'} title={titleNode(h.title,'برگ تشخیص گرفته‌اید؟ {{مهلت دارید}}')} description={h.description||'این یک متن نمونه است.'} primaryAction={{href:h.primaryHref||'#',label:h.primaryLabel||'بررسی فوری برگه‌ام'}} secondaryAction={{href:h.secondaryHref||'#deadline',label:h.secondaryLabel||'مهلت من چقدر است؟'}} icon={<path d={DOC_ICON}/>} chips={CHIPS}/><DeadlineFinderContainer id='deadline' title={s.noticesTitle||'چه چیزی به دستتان رسیده؟'} subtitle={s.noticesSubtitle||'یکی را انتخاب کنید تا مهلت نمونهٔ اعتراض و قدم بعدی را ببینید.'} notices={s.notices||NOTICES}/><StairsContainer title={s.stairsTitle||'پرونده چگونه بالا می‌رود؟'} subtitle={s.stairsSubtitle||'اگر مرحلهٔ اول نتیجه ندهد، پرونده به مرجع بالاتر می‌رود.'} steps={s.stairs||STAIRS} digits={DIGITS}/><CaseResultContainer eyebrow={r.eyebrow||'نمونه پرونده'} title={r.title||'اعتراض به برگ تشخیص مالیات'} subtitle={r.subtitle||'این یک متن نمونه است.'} text={r.text||'لایحهٔ اعتراض در مهلت قانونی تنظیم و در هیئت حل اختلاف مالیاتی دفاع شد.'} action={{href:r.actionHref||'#',label:r.actionLabel||'بررسی فوری برگه‌ام'}} stat={{to:r.statTo||70,label:r.statLabel||'کاهش جریمهٔ مالیاتی'}}/><StaticDescriptionTextContainerSecondary containerTitle={s.faqTitle||'قبل از تماس، شاید بپرسید'} contents={s.faq||FAQ}/><UserCtaContainer title={c.title||'مهلت اعتراضتان را از دست ندهید.'} subtitle={c.subtitle||'برگه یا ابلاغیهٔ خود را بفرستید تا مهلت و راه‌حل را بررسی کنیم.'} action={{href:c.actionHref||'/contact-us',label:c.actionLabel||'بررسی فوری برگه‌ام'}}/></div></MainUserLayout>}
